<?php

namespace common\models;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "user_salary_payment".
 *
 * @property int $id
 * @property int|null $user_id
 * @property int|null $salary_id
 * @property string|null $date
 * @property float|null $amount
 * @property string|null $payment_type
 * @property string|null $comment
 * @property int|null $created_at
 * @property int|null $updated_at
 */
class UserSalaryPayment extends \soft\db\ActiveRecord
{
    //<editor-fold desc="Parent" defaultstate="collapsed">


    public function behaviors()
    {
        return array_merge(parent::behaviors(), [
            TimestampBehavior::class
        ]); // TODO: Change the autogenerated stub
    }
    /**
    * {@inheritdoc}
    */
    public static function tableName()
    {
        return 'user_salary_payment';
    }

    /**
    * {@inheritdoc}
    */
    public function rules()
    {
        return [
            [['user_id', 'salary_id', 'created_at', 'updated_at'], 'integer'],
            [['date'], 'safe'],
            [['amount'], 'number'],
            [['comment'], 'string'],
            [['payment_type'], 'string', 'max' => 255],
        ];
    }

    /**
    * {@inheritdoc}
    */
    public function labels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'user_id' => Yii::t('app', 'User ID'),
            'salary_id' => Yii::t('app', 'Salary ID'),
            'date' => Yii::t('app', 'Date'),
            'amount' => Yii::t('app', 'Amount'),
            'payment_type' => Yii::t('app', 'Payment Type'),
            'comment' => Yii::t('app', 'Comment'),
            'created_at' => Yii::t('app', 'Created At'),
            'updated_at' => Yii::t('app', 'Updated At'),
        ];
    }
    //</editor-fold>

    public function getUser()
    {
        return $this->hasOne(User::class, ['id' => "user_id"]);
    }
}
